import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import GradientBackground from "../components/background/GradientBackground";

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  variable: "--font-instrument-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={instrumentSans.variable}>
      <body
        className={`antialiased font-instrument-sans`} // Adicionado a classe da fonte
      >
        <div className="flex flex-col h-[100vh] min-h-screen">
            <GradientBackground />
                        <div className="flex w-full h-full min-h-screen items-center justify-center relative z-10 p-4">
              {children}
            </div>
        </div>
      </body>
    </html>
  );
}
